### ISSUE TITLE
[opam2] cannot install metaocaml

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam-repository#10238]
```
$ opam sw create 4.04.0+BER
[ERROR] Could not resolve set of base packages:
        The following dependencies couldn't be met:
          - ocaml-variants -> base-metaocaml-ocamlfind
            unmet availability conditions: compiler = "4.02.1+BER" | compiler = "4.02.1+modular-implicits-ber" | compiler = "4.04.0+BER"


Switch initialisation failed, clean up ? ('n' will leave the switch partially installed) [Y/n] y
````
This seems to be the only package using `compiler` so I don't know immediately if it is the correct way to use this variable..

Removing
`available: [ compiler = "4.02.1+BER" | compiler = "4.02.1+modular-implicits-ber" | compiler = "4.04.0+BER" ]`
line from `/packages/base-metaocaml-ocamlfind/base-metaocaml-ocamlfind.base/opam` helps

**Comment by ygrek** [comment]
But then it is not possible to install `ocamlfind` : 
```
$ opam install ocamlfind
The actions to process have cyclic dependencies:
  - install base-metaocaml-ocamlfind.base -> install ocaml-variants.4.04.0+BER -> install ocaml.4.04.0 -> install
    conf-m4.1 -> install ocamlfind.1.7.3 -> install base-metaocaml-ocamlfind.base

```

Any ideas?

**Comment by dbuenzli** [comment]
There's an open issue about this on the opam repository https://github.com/ocaml/opam-repository/issues/7543

**Comment by ygrek** [comment]
Thanks for the lead. Removing `depopts: ["ocamlfind"]` from `base-metaocaml-ocamlfind` helped.

**Comment by ygrek** [comment]
ftr the error was : 
```

The actions to process have cyclic dependencies:
  - install base-metaocaml-ocamlfind.base -> install ocaml-variants.4.04.0+BER -> install ocaml.4.04.0 -> install
    conf-m4.1 -> install ocamlfind.1.7.3 -> install base-metaocaml-ocamlfind.base
```
and I was reading arrows as "leads to" not "depends to" and it was confusing %)

**Comment by ygrek** [comment]
Except this breaks installation because base-metaocaml-ocamlfind needs ocamlfind installed otherwise metaocaml toolchain conf is not installed.
```
install: [
  ["mkdir" "-p" "%{lib}%/findlib.conf.d/"] {ocamlfind:installed}
  ["cp" "metaocaml.native.conf" "%{lib}%/findlib.conf.d/metaocaml.conf"]
    {ocamlfind:installed & compiler = "4.04.0+BER"}
  ["cp" "metaocaml.conf" "%{lib}%/findlib.conf.d/metaocaml.conf"]
    {ocamlfind:installed & compiler != "4.04.0+BER"}
]
```
Also I figure `compiler` variable should be `ocaml:compiler`

**Comment by yallop** [comment]
These appear to be problems with the 1.2 to 2.0 conversion script (/cc @AltGr).  From the comments here and on #7543 there seem to be two issues:
  * the `compiler` constraint on `4.04.0+BER` behaves correctly with OPAM 1.2, but apparently not with OPAM 2.0 after conversion
  * the conversion script doesn't know about the `base-metaocaml-ocamlfind` package that the `4.04.0` compiler depends on, and consequently ends up creating a circular dependency.

**Comment by AltGr** [comment]
Hm, the way the `base-` packages work in 2.0 is quite limited, and doesn't seem to fit for this case. Indeed, they are marked as _dependencies_ of the compiler, which doesn't reflect the reality, and has them get installed _before_ it ; it's not a problem though, as they are expected to be virtual packages, just documenting the features. We could even skip the dependency, and have them get installed lazily, as the important part is to have compilers that _do not_ provide them marked in conflict.

@dra27 has proposed a way to define, in the compiler's `opam` file, non-virtual packages that get installed on a new switch _after_ a given compiler: this would be useful for `flexlink` (see https://github.com/ocaml/opam/issues/2649). Here, we have `ocamlfind` in between, though, so we would need to include `ocamlfind` as a base (or compiler-bundled) package too, which might not be a good idea.

Without a special mechanism, my only solution I can think of at the moment would be to modify the `ocamlfind` package itself, for example marking it as conflicting and adding a specific version for metaocaml.

On the rewriting details:
- The `compiler` variable is indeed now `ocaml:compiler`, but it is only defined in scripts (and after the `ocaml` wrapper package has been installed, i.e. not for `base-*` packages), so you cannot use `available:` anymore.
- Depending on the compiler variant should be done through `depends: "ocaml-variants" {= "4.04.0+BER" | ...}`. This is not done at the moment by the automatic rewriting, which only handles the `ocaml-version` variable (the meaning of `compiler` is more complex, and this is the only package using it AFAIK).

**Comment by yallop** [comment]
> Indeed, they are marked as dependencies of the compiler, which doesn't reflect the reality, and has them get installed before it ; it's not a problem though, as they are expected to be virtual packages, just documenting the features. 

The`base-metaocaml-ocamlfind` package works in a similar way: when it's initially installed along with the compiler it does nothing; when `ocamlfind` is subsequently installed, `base-metaocaml-ocamlfind` is rebuilt, and adds some configuration files to the `ocamlfind` installation.  With that in mind, do you think the existing MetaOCaml set-up could be made to work with OPAM 2.0?

> and this is the only package using it AFAIK

Possibly, but the [`base-flambda` package](https://github.com/ocaml/opam-repository/blob/master/packages/base-flambda/base-flambda.base/opam) could be set up in a similar way, and perhaps should be.

**Comment by AltGr** [comment]
> Possibly, but the base-flambda package could be set up in a similar way, and perhaps should be.

Indeed, it is... but there the conversion seems to be done properly. I think it's the fact that `base-metaocaml-ocamlfind` is explicitely listed as a base package [here](https://github.com/ocaml/opam/blob/35d5ba514b6cb701548ab97281d55572456d2d04/src/client/opamAdminRepoUpgrade.ml#L111) (while `base-flambda` is not, it's just a normal virtual package), that makes it not be rewritten as expected (`base` packages need to _not_ have `ocaml` added to their dependencies).

One difference is that `base-flambda` gets pulled lazily, so you can use it as a dependency, but conflicting with it won't guarantee that `flambda` is not in use.

> The base-metaocaml-ocamlfind package works in a similar way: when it's initially installed along with the compiler it does nothing; when ocamlfind is subsequently installed, base-metaocaml-ocamlfind is rebuilt, and adds some configuration files to the ocamlfind installation.

Ah, neat trick. That won't work with compilers-as-packages, though, because `depopts` have two effects, ① on rebuilds, and ② on the compilation order — here the compilation order gets problematic, as the error message pointed out. This is an unfortunate consequence of to the fact that we abuse `depends:` for base packages. With @dra27's proposal, though, the trick could work again, since there is no dependency constraint between the compiler and the "also-install" package: `base-metaocaml-ocamlfind` gets installed just after the compiler, and recompiled once `ocamlfind` is installed through the normal `depopts` mechanism.

**Comment by AltGr** [comment]
https://github.com/ocaml/opam/pull/3054 provides a proper solution for this: by marking the `base` packages as `{post}` dependencies that affect the solver, but not the build ordering, we are able to have `base-metaocaml-ocamlfind` properly installed with the switch, but recompiled after `ocamlfind` due to the `depopt`.

Additional https://github.com/ocaml/opam/pull/3057 removes special treatment for the package, so that its `available:` is rewritten properly, and the switch can be installed again.

**Comment by yallop** [comment]
Thanks for handling this slightly unusual case, @AltGr!

**Comment by ygrek** [comment]
Thanks!
When will the changes be available in the repo so that I can retest?

**Comment by dbuenzli** [comment]
@AltGr does this also close https://github.com/ocaml/opam-repository/issues/7543 ?

**Comment by AltGr** [comment]
@ygrek: next beta, should be soon (maybe one or two weeks)
@dbuenzli: indeed it does, thanks!

**Comment by ygrek** [comment]
I am still experiencing this problem, I understand convert script was not yet updated?

**Comment by AltGr** [comment]
Not yet, in the meantime you can use opam master with a local clone of `opam-repository`, after running `opam admin upgrade` on it.
