### ISSUE TITLE
Confusing state of num in 4.05.0 and ocamlfind 1.7.3

### ISSUE THREAD

**Issue by rleonid** [ocaml/opam-repository#10925]
I updated my `4.05.0` switch to ocamlfind 1.7.3 and now
```
$ ocamlfind query num
ocamlfind: Package `num' not found
```
but
```
$ opam info num

=-=- num: information on all versions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
name                   num
all-installed-versions 0 [4.05.0+trunk+flambda 4.05.0+flambda 4.05.0+spacetime 4.05.0+flambda+spacetime 4.04.0 4.05.0]  1.1 [4.06.0]
all-versions           0  1.0  1.1

=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
version      0
repository   default
homepage:    https://github.com/ocaml/ocaml
bug-reports: http://caml.inria.fr/mantis/
dev-repo:    git+https://github.com/ocaml/ocaml.git
authors:     "Valérie Ménissier-Morain" "Pierre Weis" "Xavier Leroy"
license:     LGPL-2 with OCaml linking exception
depends:     "ocaml" {< "4.06.0"} "base-num"
synopsis     The Num library for arbitrary-precision integer and rational arithmetic
```
and
```
$ opam list | grep num
base-num                base         Num library distributed with the OCaml compiler
num                     0            The Num library for arbitrary-precision integer and rational arithmetic
parany                  3.0.0        Parallelize any computation over independent items, even if there is an infinite number of them.
ppx_enumerate           v0.9.0       Generate a list containing all values of a finite type
```

**Comment by dbuenzli** [comment]
Thanks for the report, maybe related to https://github.com/ocaml/opam-repository/issues/10857 didn't investigate further.  /cc @xavierleroy the maintainer of the `num` and `base-num` packages.

**Comment by xavierleroy** [comment]
I think the problem doesn't come from the `num` and `base-num` packages, but comes from ocamlfind 1.7.3.  There is a heuristics in the configure script for ocamlfind that determines whether
1. the Num library is provided by the core OCaml installation, in which case ocamlfind should provide its own META files for it, or
2. the Num library is no longer in the core OCaml installation and is handled separately (e.g. by the OPAM `num` package version >= 1), in which case someone else will install the appropriate META file, and ocamlfind itself should not.

That heuristics went through several iterations already.  In this report it looks like case 2 was selected by ocamlfind even though OCaml 4.05 falls in case 1.

**Comment by dbuenzli** [comment]
@rleonid was that a system switch ? 

If that's the case then we are in the case of https://github.com/ocaml/opam-repository/issues/10857. Basically `num` seems to be using `ocamlc -where` to install part of its files which never works on system switches. See https://github.com/ocaml/num/pull/5 and the detective work of @djs55 in #10857.

**Comment by xavierleroy** [comment]
No we are not in the case of #10857 because the present issue report is for OCaml 4.05.  In OCaml 4.05 the num package cannot even be installed, so the problem is with ocamlfind's heuristics as I described above.

**Comment by dbuenzli** [comment]
Thanks @xavierleroy indeed I missed the `4.05` it seems upstream [has this](https://gitlab.camlcity.org/gerd/lib-findlib/commit/180a45191673775d944ac40831cc289e7e4a622a) on master as its last commit I don't know if that solves the issue but it seems it never made to a release. @gerdstolpmann could you confirm that this solves the issue and would it please be possible to make a release.

Could anyone please get in touch with upstream.

**Comment by gerdstolpmann** [comment]
@rleonid Can you try to pin ocamlfind?
```
opam pin add ocamlfind https://gitlab.camlcity.org/gerd/lib-findlib.git
```
Does it solve the problem?

**Comment by rleonid** [comment]
Apologies for the delay, and unfortunately the problem persists after the pin as well.
I should also note that I'm using `opam` 2.0.0+beta3. Unless the problem is obvious, perhaps it isn't worth expanding too much more effort? I'll move to 4.06 some time soon and I'm fine with ocamlfind 1.7.2 while on 4.05.

**Comment by rleonid** [comment]
I tried a completely fresh 4.05.0 switch and wasn't able to reproduce. I think that somehow my switch got into an awkward state. I'll close to stop diverting attention.

**Comment by XVilka** [comment]
@gerdstolpmann your pin doesn't builds as well:
```
opam pin add ocamlfind https://gitlab.camlcity.org/gerd/lib-findlib.git
[NOTE] Package ocamlfind is already pinned to git+https://gitlab.camlcity.org/gerd/lib-findlib.git (version 1.7.1.git).
[ocamlfind.1.7.1.git] no changes from git+https://gitlab.camlcity.org/gerd/lib-findlib.git
[NOTE] Converting format of /home/akochkov/.opam/default/.opam-switch/sources/ocamlfind/opam from 1.2 to 2.0~beta5
ocamlfind is now pinned to git+https://gitlab.camlcity.org/gerd/lib-findlib.git (version 1.7.1.git)

The following actions will be performed:
  ∗  install ocamlfind  1.7.1.git* 
  ∗  install ocamlify   0.0.1      
  ∗  install base-bytes base       
  ∗  install oasis      0.4.10     
  ∗  install cppo       1.6.0      
===== ∗  5 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[cppo.1.6.0] found in cache
[oasis.0.4.10] found in cache
[ocamlify.0.0.1] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The installation of ocamlfind failed at "cp ocaml-stub /home/akochkov/.opam/default/bin/ocaml".
Processing  2/10: [ocamlfind: rm]
#=== ERROR while installing ocamlfind.1.7.1.git ===============================#
# context      2.0.0~beta6 | linux/x86_64 | ocaml-system.4.05.0 | pinned(git+https://gitlab.camlcity.org/gerd/lib-findlib.git#180a4519)
# path         ~/.opam/default/.opam-switch/build/ocamlfind.1.7.1.git
# command      /usr/bin/cp ocaml-stub /home/akochkov/.opam/default/bin/ocaml
# exit-code    1
# env-file     ~/.opam/log/ocamlfind-26354-ad6566.env
# output-file  ~/.opam/log/ocamlfind-26354-ad6566.out
### output ###
# /usr/bin/cp: cannot stat 'ocaml-stub': No such file or directory



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
┌─ The following actions were aborted
│ ∗  install base-bytes base
│ ∗  install cppo       1.6.0
│ ∗  install oasis      0.4.10
│ ∗  install ocamlify   0.0.1
└─ 
┌─ The following actions failed
│ ∗  install ocamlfind 1.7.1.git
└─ 
╶─ No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by XVilka** [comment]
And yes, I have the same error with ocamlfind 1.7.3:
```
#=== ERROR while compiling text-tags.master ===================================#
# context      2.0.0~beta6 | linux/x86_64 | ocaml-system.4.05.0 | git+https://github.com/BinaryAnalysisPlatform/opam-repository.git#testing
# path         ~/.opam/default/.opam-switch/build/text-tags.master
# command      /usr/bin/make
# exit-code    2
# env-file     ~/.opam/log/text-tags-14985-637bd5.env
# output-file  ~/.opam/log/text-tags-14985-637bd5.out
### output ###
# ocaml setup.ml -quiet -build 
# ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package core_kernel -package findlib -package ppx_driver.ocamlbuild myocamlbuild.ml /home/akochkov/.opam/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# + ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package core_kernel -package findlib -package ppx_driver.ocamlbuild myocamlbuild.ml /home/akochkov/.opam/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# ocamlfind: Package `num' not found - required by `core_kernel'
# Command exited with code 2.
# make: *** [Makefile:8：build] 错误 1
```

**Comment by XVilka** [comment]
Manual pinning of ocamlfind to 1.7.1 version solved the problem

**Comment by AltGr** [comment]
I might have an idea where this issue could come from.

In the following scenario (which would explain it doesn't happen in new switches):
- start from a working switch with `ocamlfind` + `base-num` + `num.0`
- upgrade or reinstall `ocamlfind`

opam 1.2 always removed packages prior to recompiling, but opam 2.0, in order to limit the consequences of a failed build as much as possible, will first do the build and then, only if successful, uninstall all the dependents, the package itself, and install the newly compiled version before recompiling the dependents.

This means that `ocamlfind` is recompiled while its older version is still installed: could its own `META` file confuse its heuristics ?

Another possibility could be caused by the fact that `ocamlfind` does the detection _at compile time_, which means it's dependent on the state of the `num` package when compiling, while it doesn't have any dependency or depopt towards `num` (or even `base-num`). This breaks opam's expectations.

In addition, `num` has the dependency towards `ocamlfind` marked `build`, which means it doesn't need recompiling, and will always stay in place while `ocamlfind` is recompiled. That could also break `ocamlfind`'s heuristics, and make it expect an external definition, so it doesn't install the `META` file for the built-in `num` library.

Ideally, the `./configure` of ocamlfind should have a flag to override its heuristics, and its `opam` file could use e.g. `"./configure" "--with-num" {base-num:installed} "--without-num" {!base-num:installed}`.

**Comment by AltGr** [comment]
(reopened because of https://github.com/ocaml/opam/issues/3355)

**Comment by dra27** [comment]
@AltGr - I've just arrived at the same conclusion and verified it.

**Comment by RalfJung** [comment]
> OK, I think I've diagnosed the problem: if I install num in a switch with ocaml-base-compiler >= 4.06.0 and then switch back to a system switch but don't run eval $(opam env)` and then reinstall ocamlfind then ocamlfind doesn't install its num package.

It's possible I made this mistake earlier when setting up the switch, but before I ran the commands above I specifically ran `opam switch` to see if it tells me about environment variables being wrong, and it did not. But it seems that theory is gone now anyway.

> It's entirely to do with reinstalling ocamlfind.

Indeed, repeatedly running `opam reinstall ocamlfind` makes it ping back and forth between finding and not finding num. Funny. At least I have a work-around now.

**Comment by dra27** [comment]
One option is to fix it in opam-repository only: simply to re-run configure in the `install` step. At this point, even on a reinstall, the package has been uninstalled. This causes findlib to regenerate the correct `META` files and reinstall them. The downside is that because `Makefile.config` is regenerated, the findlib library is recompiled and `num_top.cma` is only ever built during the `install` stage. So this solution works, but it wastes a little time and it's impure.

The other option is to "fix" findlib upstream. However, I can see a case for both changing and not changing - it's not clear to me why you should absolutely be able to `configure` a new version of `ocamlfind` **before** uninstalling the previous one. Depends on what @gerdstolpmann thinks of this.

**Comment by RalfJung** [comment]
I just hit this problem again, still trying to convince ocamlfind that I have num installed. The tag says "needs reporter action", but what action is needed? Seems to me like the issue has been diagnosed and needs someone to care enough to fix it.

**Comment by RalfJung** [comment]
This is still a problem. Seems like ocamlfind is basically unmaintained, with such critical bugs going unfixed for years? That's quite concerning for such a core piece of infrastructure.

Cc @kit-ty-kate @dra27 (recently committing to ocamlfind package here)

**Comment by gerdstolpmann** [comment]
@RalfJung This is not a critical bug because it only affects one library. It's also not clear that the problem is caused by ocamlfind - it's more that opam changed the way it reinstalls packages in a way that is incompatible with the way ocamlfind detects the presence of num. I'm not sure that there is a solution that always works.

Anyway, I've created https://github.com/ocaml/ocamlfind/issues/1 which happens to be the first issue after the move of the ocamlfind repo to github.

**Comment by RalfJung** [comment]
> This is not a critical bug because it only affects one library

It is a critical bug for that one library though, making it and all of its 63 reverse dependencies unusable each time `ocamlfind` gets updated. Not sure who maintains `num`. Nobody, from the looks of it.

>  I'm not sure that there is a solution that always works.

I feel like in one of these bad jokes where people run from office to office and everyone just tells me that this is not their department. The fact is that we have a horrible user experience for this `num` package, which regularly gets into a state that is unfixable for most users. And this has been going on for well over a year.

---

Some variant of this bug just grinded our entire CI (around 15 repositories) to a halt. They are now all in a state where all that happens is this error:
```
# /usr/bin/make -C src install
# make[1]: Entering directory '/builds/iris/iris/opamroot/ocaml-base-compiler.4.07.1/.opam-switch/build/num.1.3/src'
# install -d /builds/iris/iris/opamroot/ocaml-base-compiler.4.07.1/lib/ocaml
# sed -e 's/%%VERSION%%/1.3/g' META.in > META
# ocamlfind install num META
# ocamlfind: Package num is already installed
#  - (file /builds/iris/iris/opamroot/ocaml-base-compiler.4.07.1/lib/num/META already exists)
```
And because this is CI, I cannot just run some random interactive commands to fix this. CI can only work well on a foundation of reliable software, and, well, we seem to be lacking that.

**Comment by AltGr** [comment]
Wow, had completely forgotten about this and thought it was fixed a long time ago... sorry @RalfJung, and you are right to ping the maintainers.

If my diagnostic above is still correct, the issue is that opam assumes that you declare anything that is "observable" to you; here `num` happens to be observable by `ocamlfind`'s conigure, although it doesn't fit in any of the existing `depends:`/`depopts:`/`{post}`/`{build}`/... possible declarations.

This might be a case for a `depopt: "num" {post}`, which I had discarded from the spec (and opam will reject) as useless... but that seems a bit far-fetched, although it seems sound, kind of.

A better fix IMHO would be to patch ocamlfind's detection heuristics so as to not install anything for `num` ; a dirty workaround (fixing `num` to remove the META file before trying to install) could also work...

**Comment by AltGr** [comment]
I have not tried to reproduce with it, but think the PR above should avoid the issue.
A cleaner fix would be to have options in `ocamlfind`'s `./configure`, and pass them through the `opam` file, instead of patching.
Also, this is also on `ocamlfind.1.8.1`.

**Comment by dra27** [comment]
I think a cleaner solution may be to do as I did with the `graphics` package - uncouple the dependency on `ocamlfind` in the `num` package and make `num` a `depopt` of `ocamlfind`?

**Comment by dra27** [comment]
(sorry, I too had forgotten about this...)

**Comment by AltGr** [comment]
That may be best indeed

**Comment by dra27** [comment]
@RalfJung - is this CI system public? It'd be handy to see more of the console logs from the builds.

**Comment by RalfJung** [comment]
Yes, you can see examples of failing jobs at https://gitlab.mpi-sws.org/iris/iris/pipelines/21401.

Since then we purged the CI cache for all our projects, which unblocked CI -- the issue, as usual, only arises when *upgrading* num and/or ocamlfind, not in new installations.

**Comment by RalfJung** [comment]
AFAIK this is still a problem.

**Comment by RalfJung** [comment]
Here's how to reproduce this problem:
```
opam switch create numbug ocaml-base-compiler.4.05.0
# enter that switch
opam install num.0
opam install ocamlfind
ocamlfind query num # works fine
opam reinstall ocamlfind
ocamlfind query num # broken
```
I do not think I have seen this happen with switches for newer versions of ocaml.

**Comment by roddyyaga** [comment]
I'm getting this on more recent versions of OCaml too:
```
opam switch create . --empty
opam install ocaml.4.11.1
opam install num.1.4    # Errors as num is already (somewhat) installed
```

**Comment by kit-ty-kate** [comment]
I managed to reproduce and fix the issue:
```
FROM ocaml/opam:debian-10-opam
RUN opam switch create numbug ocaml-base-compiler.4.05.0
RUN sudo apt-get install -yy m4
ENV OPAMPRECISETRACKING=1
RUN opam remote set-url default git://github.com/kit-ty-kate/opam-repository.git#fix-ocamlfind
RUN opam install -y num.0
RUN opam install -y ocamlfind
RUN opam exec -- ocamlfind query num
RUN opam reinstall -y ocamlfind
RUN opam exec -- ocamlfind query num
```
This fix consists of simply calling `./configure` again in the install phase, which happens after the previous installation of ocamlfind is removed. Ultimately I think the proper fix should be for ocamlfind to add an option to its configure script to enable or not the installation of the META file for a builtin library, the same way it was done for camlp4 with the `-no-camlp4` argument.

I've opened a PR here: https://github.com/ocaml/opam-repository/pull/17891

**Comment by dra27** [comment]
Further to this, ocamlfind 1.9.1 includes an overhaul of the detection of installed `META` files, so this issue is hopefully permanently gone!
