### ISSUE TITLE
Try to install camlp5 with latest version of ocaml delete everything on the file system

### ISSUE THREAD

**Issue by LukeXuan** [ocaml/opam-repository#11440]
I'm not familiar with the internal mechanics of opam install. But it seems like the camlp5 is not compatible with ocaml 4.06.1, and it complains about it during configuration. As a result, several variables is not set in the Makefile. The opam will execute "make uninstall" then which essentially runs "rm -rf /" on my computer.

**Comment by mseri** [comment]
I think this should be fixed also in the [camlp5 makefile](https://github.com/camlp5/camlp5/blob/master/Makefile#L58), maybe setting the `DESTDIR` to some dummy tmp value or aborting the commands if `DESTDIR` and/or `CAMLP5N` are not set.

**Comment by thierry-martinez** [comment]
Camlp5 `Makefile` is now fixed (@roglo): https://github.com/camlp5/camlp5/commit/d5616932193a05d4cffeb46deda7c003f9e38aca

**Comment by mseri** [comment]
Thanks!

**Comment by AltGr** [comment]
Ref: https://github.com/ocaml/opam/issues/3231
Maybe we need to enable sandboxing where available ASAP. This is really not nice...

For the story, this happened to me a long time ago (exactly the same: undefined variable in a Makefile resulting in `rm -rf /`. Plus it was running from emacs so I didn't notice it was taking suspiciously long before it was too late). That was a few days before the end of a project... I have adopted a very defensive style whenever I need to use `rm -rf` in scripts or Makefiles ever since. I always use `rm -rf /tmp/${VAR#/tmp/}` to remove temp dir `$VAR` from scripts.

**Comment by avsm** [comment]
Indeed, this is a strong case to enable sandboxing in opam2 where at all possible.
