### ISSUE TITLE
opam install curses fails because of <term.h>

### ISSUE THREAD

**Issue by neilpanchal** [ocaml/opam-repository#12710]
Installing curses fails because it cannot locate <term.h>

![image](https://user-images.githubusercontent.com/8161031/46173151-5133e200-c25a-11e8-9646-2a40754eda05.png)

I checked by running `opam depext curses.1.0.3` and all system dependencies are installed. Why doesn't it find `<term.h>`?

I checked that `libncurses5-dev` is successfully installed on my system (Ubuntu 18.04).

**Comment by ogunden** [comment]
The problem is fixed upstream in curses.1.0.4. I have an updated tarball and a .opam file that should work to fix it, but I can't get the new opam repository to publish.

The new file is this, in case anyone else wants to try and publish the new version:

`opam-version: "2.0"
maintainer: "ogunden@phauna.org"
authors: ["Nicolas George"]
homepage: "https://www.nongnu.org/ocaml-tmk/"
bug-reports: "http://savannah.nongnu.org/projects/ocaml-tmk/"
dev-repo: "git+https://git.savannah.nongnu.org/git/ocaml-tmk.git"
build: [
  ["./configure" "--enable-widec"]
  [make "OCAMLMAKEFILE=OCamlMakefile" "byte"]
  [make "OCAMLMAKEFILE=OCamlMakefile" "opt"]
]
remove: [["ocamlfind" "remove" "curses"]]
depends: ["ocaml" "ocamlfind"]
depexts: [
  ["libncurses-dev"] {os-distribution = "ubuntu"}
  ["libncurses-dev"] {os-distribution = "debian"}
]
install: [make "OCAMLMAKEFILE=OCamlMakefile" "install"]
synopsis: "Bindings to curses/ncurses"
description: "Tools for building terminal-based user interfaces"
flags: light-uninstall
url {
  src: "http://ocaml.phauna.org/distfiles/ocaml-curses-1.0.4.ogunden1.tar.gz"
  checksum: "md5=b734aae5b9087fa482a2b283f9ace328"
}
`

**Comment by ogunden** [comment]
The issues I'm having with opam are as follows:

,,,
ubuntu@ip-172-31-32-41:~/opam-repository-2/packages/curses/curses.1.0.4$ opam install .
[NOTE] Package curses is currently pinned to file:///home/ubuntu/.opam/repo/default/packages/curses/curses.1.0.4 (version 1.0.4).
curses is now pinned to file:///home/ubuntu/opam-repository-2/packages/curses/curses.1.0.4 (version 1.0.4)
The following actions will be performed:
  ∗ install curses 1.0.4*

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[curses.1.0.4] synchronised from file:///home/ubuntu/opam-repository-2/packages/curses/curses.1.0.4

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of curses failed at "/home/ubuntu/.opam/opam-init/hooks/sandbox.sh build ./configure --enable-widec".

#=== ERROR while compiling curses.1.0.4 =======================================#
# context     2.0.1 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(file:///home/ubuntu/opam-repository-2/packages/curses/curses.1.0.4)
# path        ~/.opam/default/.opam-switch/build/curses.1.0.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --enable-widec
# exit-code   1
# env-file    ~/.opam/log/curses-4917-58c514.env
# output-file ~/.opam/log/curses-4917-58c514.out
### output ###
# bwrap: execvp ./configure: No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build curses 1.0.4
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    libncurses-dev
```

and 

```
ubuntu@ip-172-31-32-41:~/opam-repository-2/packages/curses/curses.1.0.4$ opam publish http://ocaml.phauna.org/distfiles/ocaml-curses-1.0.4.ogunden1.tar.gz .

The following will be published:
  - curses version 1.0.4 with opam file at /home/ubuntu/opam-repository-2/packages/curses/curses.1.0.4/opam
    archive at http://ocaml.phauna.org/distfiles/ocaml-curses-1.0.4.ogunden1.tar.gz


Continue ? You will be shown the patch before submitting. [Y/n] y
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/bin/git fetch --multiple origin user" exited with code 128 "fatal: not a git repository (or any of the parent directories): .git"
```
