### ISSUE TITLE
Change forge.ocamlcore.org -> forge-static.ocamlcore.org for branch 1.2

### ISSUE THREAD

**Issue by db4** [ocaml/opam-repository#13251]
Please apply changes from https://github.com/ocaml/opam-repository/commit/ed830cc708031a7229577b49113e021cb68521c0 to branch 1.2 as well. Currently it's broken, e.g.:
```
[ounit: http] Command started
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ounit.2.0.8
        (This may be fixed by running 'opam update')
```

**Comment by echa** [comment]
Same issue here with https://github.com/ocaml/opam-repository/blob/master/packages/calendar/calendar.2.04/opam

```
[ERROR] The sources of the following couldn't be obtained, aborting: 
  - calendar.2.04: Curl failed
```

This issue relates to all packages hosted at http://forge.ocamlcore.org because the server is down currently.

Related server discussion is at https://discuss.ocaml.org/t/forge-ocamlcore-org-is-down-use-forge-static-ocamlcore-org-for-now/3152
