### ISSUE TITLE
conf-libssl doesn't build on osx

### ISSUE THREAD

**Issue by Bronsa** [ocaml/opam-repository#15295]
```
[~]> opam install conf-libssl
The following actions will be performed:
  ∗ install   conf-libssl      1
  ↻ recompile ssl              0.5.9 [uses conf-libssl]
  ↻ recompile conf-openssl     1     [uses conf-libssl]
  ↻ recompile lwt_ssl          1.1.2 [uses ssl]
  ↻ recompile conduit-lwt-unix 2.0.1 [uses lwt_ssl]
  ↻ recompile cohttp-lwt-unix  2.3.0 [uses conduit-lwt-unix]
===== ∗ 1   ↻ 5 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[lwt_ssl.1.1.2] found in cache
[ssl.0.5.9] downloaded from cache at https://opam.ocaml.org/cache
[cohttp-lwt-unix.2.3.0] downloaded from cache at https://opam.ocaml.org/cache
[conduit-lwt-unix.2.0.1] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫

#=== ERROR while compiling conf-libssl.1 ======================================#
"./osx-build.sh": command not found.


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build conf-libssl 1
└─
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    openssl
```

**Comment by kit-ty-kate** [comment]
Is it fixed by https://github.com/ocaml/opam-repository/pull/15331?

**Comment by Bronsa** [comment]
I'm not in front of a laptop right now, but https://github.com/ocaml/opam-repository/pull/15330 fixes conf-libssl on macos. 

Your change should make conf-openssl.1 installable again which is great, but conf-libssl should still be broken

**Comment by kit-ty-kate** [comment]
I'm not too sure to understand how it worked before. The code to of `build` section didn't change. I'll merge it anyway as soon as the macos CI is green but I'm a bit puzzled.

**Comment by Bronsa** [comment]
Maybe some recent change to opam? it looks like the +x flag is cleared
after the file is installed locally

**Comment by reykjalin** [comment]
I had this same issue using [esy]() v0.6.2, with `openssl` installed from Homebrew.

The problem turned out to be because openssl is saved in `/usr/local/opt/openssl@1.1`, and not `/usr/local/opt/openssl` like the `osx-build.sh` script expects.

I assume this means the script will have to be modified to find the relevant openssl version installed by homebrew?
I was able to fix this by symlinking `openssl@1.1` to `openssl` via `sudo ln -s /usr/local/opt/openssl@1.1/ /usr/local/opt/openssl` but I'm not sure that's a good idea on a system-wide level.

I'll gladly open a new issue for this if that's better, but decided it'd fit better here for now.

**Comment by kit-ty-kate** [comment]
Is there a brew command to find the location of an installed file by a specified package?

**Comment by mseri** [comment]
I don't thinks so, but it would be enough make the libpath configurable and use brew openssl suggestion:
```
❯ brew info openssl
openssl@1.1: stable 1.1.1d (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1d (7,983 files, 17.9MB)
  Poured from bottle on 2019-09-20 at 14:31:23
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 426,506 (30 days), 1,265,472 (90 days), 3,829,359 (365 days)
install-on-request: 51,897 (30 days), 169,797 (90 days), 538,812 (365 days)
build-error: 0 (30 days)
```

**Comment by kit-ty-kate** [comment]
It turns out `/usr/local/opt/openssl@1.1` is a link to the Cellar/openssl directory so `brew --prefix <pkg>` should work I suppose. I have a proposed fix in https://github.com/ocaml/opam-repository/pull/16112. @reykjalin could you tell me if it fixes your issue?

**Comment by reykjalin** [comment]
After applying the fix I can now build `conf-openssl`, but I think being able to do that just unearthed an issue in building `async_ssl`:

```
$ esy build                                                                                                                                         0
info esy build 0.6.2 (using package.json)
info building esy-skia@github:revery-ui/esy-skia#91b10c9@d41d8cd9
info building @opam/async_ssl@opam:v0.12.0@5687fe11
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/async_ssl@opam:v0.12.0
    # esy-build-package: pwd: /Users/kristofer/.esy/3/b/opam__s__async__ssl-opam__c__v0.12.0-83275035
    # esy-build-package: running: 'dune' 'build' '-p' 'async_ssl' '-j' '4'
            bash bindings/discover.exe (exit 1)
    (cd _build/default/bindings && /usr/local/bin/bash -e -u -o pipefail -c 'gcc -O2 -fno-strict-aliasing -fwrapv $(< openssl-ccopt) discover.c $(< openssl-cclib) -ldl -o discover.exe')
    discover.c:2:10: fatal error: 'openssl/ssl.h' file not found
    #include <openssl/ssl.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command failed: 'dune' 'build' '-p' 'async_ssl' '-j' '4' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/async_ssl@opam:v0.12.0
esy: exiting due to errors above
```

This seems to be more of an issue with how Homebrew refuses to link the `openssl` library since `libressl` comes pre-installed on macs. I'm not sure if this is something `opam` should be fixing.
I can fix this issue by symlinking to the `openssl@1.1` folder like I did [before](https://github.com/ocaml/opam-repository/issues/15295#issuecomment-606186272).

I've tried following the instructions from `brew info` posted by @mseri above, but that doesn't fix the issue.

When I run `brew link openssl` I get the following prompt:

```
$ brew link openssl
Warning: Refusing to link macOS-provided software: openssl@1.1
If you need to have openssl@1.1 first in your PATH run:
  echo 'set -g fish_user_paths "/usr/local/opt/openssl@1.1/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find openssl@1.1 you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/openssl@1.1/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  set -gx PKG_CONFIG_PATH "/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

And `brew info` contains the following:

>openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
>because openssl/libressl is provided by macOS so don't link an incompatible version.

Which is why I think Homebrew is not linking the library properly.

**Comment by mseri** [comment]
Sorry for not being clearer. My suggestion would also have required changing the conf-libssl to work.

Concerning `async_ssl`, the package discovery uses pkg-config so the installation should work if you provide `PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"` or `PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig"`. E.g. `PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig" opam install async_ssl` should work fine.

There should be a way to set either of those in esy build environment, but it's a tool that I don't know so I cannot help there.

**Comment by reykjalin** [comment]
>There should be a way to set either of those in esy build environment

I'm not sure that's the case since esy is [built to use a clean environment](https://esy.sh/docs/en/environment.html#build-environment) for builds:

>`$SHELL` is set to `env -i /bin/bash --norc --noprofile` so each build is executed in an environment clear from user customizations usually found in `.profile` or other configuration files.

You can modify the environment or create environment variables for your package, but that doesn't apply to other packages afaict.

So I arrive at the conclusion that people using `esy` will just have to set up their system such that a vanilla bash environment can find the package 🙂.
From my perspective, the issue seems to be fixed for opam. Thanks for looking into this!

**Comment by kit-ty-kate** [comment]
> From my perspective, the issue seems to be fixed for opam. Thanks for looking into this!

I just hope my fix doesn't just move the problem to individual packages

**Comment by mseri** [comment]
In that case, brew is explicitly saying to use a custom PKG_CONFIG_PATH though, so there is not much more we can do.

**Comment by kit-ty-kate** [comment]
It seems that we've hit the case in the CI here: https://github.com/ocaml/opam-repository/pull/16122#issuecomment-607331619

I'm not sure what to do to improve this issue

**Comment by mseri** [comment]
What if we change 
```diff
- res=$(env PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig pkg-config openssl)
+ res=$(env pkg-config openssl)
```
And add a post failure message for brew saying look at brew info openssl and set the appropriate PLG_CONFIG_PATH?

**Comment by kit-ty-kate** [comment]
I looked back why it was the way it was in the beginning and stubbled upon this PR: https://github.com/ocaml/opam-repository/pull/10453

The TL;DR is that on osx there is already one openssl library that was(?) installed and the check was there to force user to use the one from homebrew instead of the system one. (if I understand the thing correctly)

Maybe showing a warning (instead of an error) to the users is sufficiant in case they are using MacOS? To ensure users double-check they are using the right one? Or something like that?

**Comment by mseri** [comment]
Seems reasonable
