### ISSUE TITLE
[RFD] versioning policy; maintenance of obsolete packages

### ISSUE THREAD

**Issue by jrochel** [ocaml/opam-repository#15392]
On the issue https://github.com/ocaml/opam-repository/pull/15352 I'm encountering the problem that several "obsolete" versions of ocsigen-toolkit are not installable anymore, due to compatibility issues and that I had to go fix them all, one by one.

So far most of the ocsigen team has pursued the following versioning policy:
- major version: API-breaking changes
- minor version: new functionalities and other improvements
- patch: bugfixes and compatibility issues

That means that there should be never a situation where a user would prefer installing version 6.3.3 over 6.3.4. Therefore there is never a need update the definition of version 6.3.3 once 6.3.4 has been released.

However, the versioning policy on opam seems to be that every single released version should be updated and maintained. These two policies are clearly in conflict with one another: if 6.3.3 is no longer installable due to some changes in some dependency now I'd have to
- update the opam file and release a version 6.3.4 (according to the ocsigen policy)
- update the opam file and re-release version 6.3.3 (according to the opam policy)

which leads to the situation that version 6.3.3 and 6.3.4 are identical. (This now currently the case for ocsigen-toolkit.2.2.0 / ocsigen-toolkit.2.2.1 according to my latest PRs.)

Apart from reforming the opam policy the following two solutions come to mind:
- We no longer publish versions 6.3.3 and 6.3.4 on opam but maintain only a version 6.3 which will evolve over time by being kept up-to-date with the latest working version of that release (6.3.4).
- We make PRs to delete obsolete versions (6.3.3) from opam.

I'm eager to read your comments and suggestions.

**Comment by avsm** [comment]
The basic problem is that this assertion is generally not true:
```
That means that there should be never a situation where a user would prefer installing version 6.3.3 over 6.3.4. Therefore there is never a need update the definition of version 6.3.3 once 6.3.4 has been released.
```

While we would obviously prefer a world where upgrades never break anything, this is not how the majority of released software works in the wild -- users should have the choice of version upgrades. Therefore, the idea is that if a combination of package versions installed at some point, it should continue to be installable in the future, along with more combinations via newly released software.

However, you should _never_ have to re-release an older version -- you simply modify the package metadata in opam-repository to add upper bounds where appropriate to restrict the allowable package combinations.

So this isn't quite right:
>  if 6.3.3 is no longer installable due to some changes in some dependency now I'd have to
> - update the opam file and release a version 6.3.4 (according to the ocsigen policy)
> - update the opam file and re-release version 6.3.3 (according to the opam policy)

Since you don't need to re-release version 6.3.3. Just adjust the opam metadata in this repository to add an upper bound to dependencies.  If 6.3.4 is just a point release and doesn't change interfaces, then users will naturally upgrade to it when they do an opam update.

If you're _very_ confident that point releases will never break users, then we don't really want to stop in your way and prevent you from deleting older releases. However, I don't think there's ever been a library that hasn't messed up something in the compatibility matrix at some point, and deleting older releases prevents users from rolling back to a working setup.

**Comment by jrochel** [comment]
Thanks. That makes things clearer. These things should be documented in some guidelines somewhere.
