### ISSUE TITLE
conf-ida: make the search script a bit less aggressive

### ISSUE THREAD

**Issue by Armael** [ocaml/opam-repository#15643]
cc @ivg 

I was trying to understand why my build was stuck trying to install `conf-ida`. Turns out it was frantically exploring the 8TB storage server mounted in `/tmp/nas` (a bit of a scary thing to discover).

Could the discovery script be made a bit less aggressive, and for instance avoid crossing filesystem boundaries?

**Comment by ivg** [comment]
So here is the story, before opam 2.0 we were relying on locate on Linux and on mdfind on Mac. Both are not performing any searches, but make queries to the file database, which is fast. However, opam 2.0 is sandboxed so we can't access the locatedb anymore in opam 2.0 and we had to fall back to the `find` utility. We can tweak the search a bit and do not follow the tmp folder and other folders that are well-known for not storing user data, e.g., `/proc` or `/sys`. We could also add a timeout and stop searching after some number of seconds.

However, the general idea is that search is the last resort and we provide a few options for a user to set the IDA Pro folder. The very first option is to tell opam explicitly where it is located using `opam config`, e.g.,
```
opam config set ida-path /path/to/ida/folder
```
If this global variable is set no searches will be executed.

The second option is to specify the `IDA_PATH` environment variable. The third option is to add a folder with idaq executable to  `PATH`, so that `which idaq` returns the path. Only after that, the fourth attempt would be to extensively search the file system. 

cc @gitoleg

**Comment by Armael** [comment]
Thank you for the details. For the record, I've hit this issue not because I wanted to install this package in particular, but because we've been hacking with @gasche on some tool that tries to build "all opam packages".

In that setting, we would simply like for the search to behave "nicely enough" and timeout without blocking the build (since most likely, the CI machine won't have IDA).

> We can tweak the search a bit and do not follow the tmp folder and other folders that are well-known for not storing user data, e.g., /proc or /sys. We could also add a timeout and stop searching after some number of seconds.

That would be very good :).

**Comment by ivg** [comment]
Ok, so the simple and easy to implement solution would be wrapping the find into `timeout`, e.g, `timeout 10 find ....` and checking the exit status. 

Any objections? If not, then I will push the fix soonish (I'm currently working on Ghidra support (an open source alternative for IDA from NSA), so I will update both the newly comming `conf-ghidra` and the existing `conf-ida` scripts (both versions), to be more respectful to the user time).

**Comment by Armael** [comment]
I would be also more comfortable if `/tmp` and friends are excluded from the search, or if the `-mount` option is passed to find. Otherwise, that sounds good, yes.

**Comment by ivg** [comment]
To clarify, more comfortable in addition to timeout or instead of timeout?

I'm also a little bit reluctant to add the `-mount` option, as it is quite common when `/srv`, `/opt`, /home` and `/` all are mounted on different partitions. So adding the `-mount` option would defeat the whole purpose of the extensive search, so probably instead of adding `-mount` we can just stick to search in the home folder only. The impact will be roughly the same.

**Comment by Armael** [comment]
I meant in addition to the timeout.

> I'm also a little bit reluctant to add the -mount option, as it is quite common when /srv, /opt, /homeand/all are mounted on different partitions. So adding the-mountoption would defeat the whole purpose of the extensive search, so probably instead of adding-mount` we can just stick to search in the home folder only. The impact will be roughly the same.

Ok, fair enough. I trust you to do the reasonable thing then!

**Comment by Armael** [comment]
(I think the issue still stands?)

**Comment by gasche** [comment]
I suspect that the bot closed the issue by mistake. In any case, unless @ivg clarifies that things have changed, we have a relatively badly-behaved configuration script in the opam repository.

@ivg: another possibility would be to improve the opam sandboxing script to whitelist the locatedb/modfind repositories. If I remember correctly, I sent a PR upstream to whitelist `ccache`'s cache repository for a similar reason.

**Comment by Armael** [comment]
erm...

**Comment by ivg** [comment]
Nothing has changed and it is our debt, @gitoleg can you take it and fix it? We indeed forget about it, sorry, just recently noticed that it's still unresolved. Will take care of it now.

**Comment by gitoleg** [comment]
I will fix it!

**Comment by gasche** [comment]
Thanks for the fix!
