### ISSUE TITLE
Z3 4.8.7 version does not link with libstdc++.so correctly

### ISSUE THREAD

**Issue by douglastt** [ocaml/opam-repository#15949]
The opam file of z3.4.8.7 seems to use the `-staticlib` option when compiling z3 binaries, which makes the `libstdc++.so` lib not linked correctly.

**Comment by mseri** [comment]
@anton-trunov do you know if this is still an issue with more recent releases of `z3`? Is it possible to fix it at the opam-repository level or requires changes in z3 build itself?

**Comment by anton-trunov** [comment]
@ivg recently did a big refactoring on the `z3` package. I think he is way more qualified to comment on this.

**Comment by ivg** [comment]
> @anton-trunov do you know if this is still an issue with more recent releases of `z3`? Is it possible to fix it at the opam-repository level or requires changes in z3 build itself?

@mseri,  the version 4.8.8 is fixed in the z3 master version(https://github.com/Z3Prover/z3/pull/4468), as well as the patch is added to opam 4.8.8-1 (https://github.com/ocaml/opam-repository/pull/16535), so you can benefit from it without waiting for 4.8.9.

We can theoretically backport the patch to older versions, but it will take some effort. @douglastt do you need specifically 4.8.7 or you can update to 4.8.8-1 (basically the latest opam version)?

**Comment by ivg** [comment]
Ah, wait a second, I've rushed to conclusion, this issue is about libstdc++ that is not linked statically. Maybe it is an instance of XY-problem, but the patch won't link libstdc++ statically, it is still a dynamic dependency (though it will make things transparent so that whenever you compile against z3 no problems with libstdc++ missing symbols will arise). So if @douglastt really wants it to be static, I would say it WONTFIX, since statically linking libc or libc++ is a big no-no :) They provide the OS runtime and shall never be statically linked. The https://github.com/Z3Prover/z3/pull/4468 patch does the things in right way and properly encodes depedencies on C++ in z3 libraries.
