### ISSUE TITLE
digestif not available on FreeBSD

### ISSUE THREAD

**Issue by web-vertalo** [ocaml/opam-repository#16118]
Is there a fix available to try, or a work-around to apply?

The package was marked unavailable here:

https://github.com/ocaml/opam-repository/commit/6458743d419a3ef64aafca0d5993c117d46c587a

**Comment by hannesm** [comment]
the issue is that the `patch` command on FreeBSD does not work as the one Linux. There are older digestif releases (such as 0.8.0) which work fine on FreeBSD. The "fix" would be to integrate an `echo` based solution into the opam file, as pioneered by checkseum (https://github.com/mirage/checkseum/blob/master/checkseum.opam#L21-L22) -- maybe @dinosaure will do this (back in the project, or into opam-repository) for both projects?
