### ISSUE TITLE
Duplicate depexts for suse/opensuse

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#17004]
See https://github.com/ocaml/opam-repository/pull/16864
@anuragsoni I have created this issue as a reminder, no pressure. There is no hurry

**Comment by anuragsoni** [comment]
Thanks @mseri for opening this. I'm still interested in working on the depexts for opens use tumbleweed so I'll keep this in mind :) Things have been a little busy recently but I should be able to get to this soon.

**Comment by anuragsoni** [comment]
Based on the comments in #17044 it sounds like opam 2.1 will handle this scenario by handling `suse` and `opensuse` in the same way. That'd be a nicer way to deal with this situation instead of duplicating lines for both suse/opensuse with the same content. I think this issue can be closed and i'll try opam 2.1 on opensuse and help out in the opam project if i find any issues. 
Thanks!

**Comment by mseri** [comment]
Thank you very much!

**Comment by mseri** [comment]
If anything comes up to be done at opam-repository level, let me know and I'll reopen the issue
