### ISSUE TITLE
Early warning: forge.ocamlcore.org will be shutdown on 2020-10-15

### ISSUE THREAD

**Issue by gildor478** [ocaml/opam-repository#17297]
Hi,

This is not yet officialy announced but forge.ocamlcore.org will fully shutdown on 2020-10-15.

I have identified that opam-repository could be impacted. I have prepared the transition a while back, by using an external file repository (https://download.ocamlcore.org, see #13524) but there is a chance that there will be some errors during the transition.

Can we keep this bug open to track potential problems when the shutdown will happen?

If you find any potential problems, let me know so that I can fix that early.

**Comment by avsm** [comment]
Many thanks for the notification @gildor478. Would you like to hand off the download.ocamlcore.org infrastructure as well, so that you don't have to keep it running? I can arrange for it to be hosted somewhere like dl-archive.ocaml.org perhaps.

Also, it would be nice to document the history of the OCaml Forge briefly on ocaml.org. If you have a few moments to write down the timeline of it and any statistics you might have had, I've created https://github.com/ocaml/ocaml.org/issues/1172 for that. (I'd be happy to make the changes to the website -- just need you to provide the prose).

**Comment by gildor478** [comment]
Still happy to help with OCaml ;-)

I have prepared the 2 following repositories:

- https://github.com/ocaml/download.ocamlcore.org
- https://github.com/ocaml/forge.ocamlcore.org

Both of them will push to netlify.com (this is the current setup for download.ocaml.org). This way, I will not have to keep them running. I am planning to keep paying on the ocamlcore.org domain anyway, so everything is OK on this side. I'll just have to document this, so that people knows who to contact in case of problems.

I'll send a PR to write the history of the forge -- with a few screenshots while it is still up.

**Comment by gildor478** [comment]
I have a very short down time from 00:11 AM to 1:00 AM 2020-10-16 (Paris), while I was deploying a new version. During this time, files downloaded were empty (or containing their LFS reference). This is back to normal.

**Comment by gildor478** [comment]
The forge has been down for a week and everything looks normal. Closing this bug for now, feel free to reopen.
