### ISSUE TITLE
Package install statistics, but without dependencies

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam-repository#17996]
There are two ways to deal with the real (or perceived) poor documentation of OCaml packages:

1. Have a central place for all package documentation. I believe there are efforts towards this.
2. Improve the documentation of individual packages

I want to do some of (2). But in order to focus effort, I need to know which packages are most popular. But the opam.ocaml.org statistics just tell me about raw installs of packages.

What I'd like to know is which packages are installed, but not as dependencies (i.e if someone actually types opam install x, I don't want to count that y is installed as a dependency).

Is that data available?

**Comment by avsm** [comment]
That data is not available, and we are trending in the opposite direction for GDPR reasons (not holding onto any server logs, and increasing the number of mirrors).  The data on opam.ocaml.org is very skewed due to the various CIs that hit the central system.

However, it's still possible to answer your question. A useful objective metric you could look at is the "most depended upon" packages in the dependency graph.  One of the most "requested" libraries for more end-to-end documentation is ocaml-ctypes, which gets very few contributors _vs_ how much it is used in the ecosystem.

Note that end user packages probably won't give you what you're after, as those tend to be "leaf projects" that don't need library documentation (e.g. `opam install tezos` or `opam install mirage` or `opam install .` to get local dependencies installed for your own project).

**Comment by johnwhitington** [comment]
Thanks.

> However, it's still possible to answer your question. A useful objective metric you could look at is the "most depended upon" packages in the dependency graph.

Is this just the `revdeps` column here?

http://check.ocamllabs.io

(I presume the many 2881s are not correct data, but the rest seems convincing enough).

**Comment by kit-ty-kate** [comment]
The way the `revdeps` column is set is described here: https://github.com/ocurrent/opam-health-check/blob/117a8b8d226bfcbdf0c76e8d043133154b6affde/server/backend/check.ml#L269

In short, the column means "how many packages could this package rely upon one way or another?".
This works fine to show popularity for libraries but poorly for tools, however.
