### ISSUE TITLE
conf-dbm: cannot find gdbm.h

### ISSUE THREAD

**Issue by jrochel** [ocaml/opam-repository#18581]
It seems that on Ubuntu latest conf-dbm does not seem to find gdbm.h (which is part of libgdbm-dev): https://github.com/ocsigen/ocsigenserver/runs/2436215821?check_suite_focus=true

Does anybody have an insight into why?

**Comment by kit-ty-kate** [comment]
This is a known issue with opam 2.0 where the first call to `opam list --external ...` (called by opam-depext) does not return the same result as `opam install ...` when the package has a disjunction (`sqlite3 | dbm` in your case).
You can see this in your build log at the `opam depext` step above.

I can't seem to find the original issue that was opened years ago but this is fixed in opam 2.1

**Comment by jrochel** [comment]
Alright. I'll ignore these errors then (at least as long as opam < 2.1 is used).
