### ISSUE TITLE
Error: This expression has type string but an expression was expected of type bytes

### ISSUE THREAD

**Issue by yurivict** [ocaml/opam-repository#19379]
annexlib-0.13.5 fails:

```
File "strExtras.ml", line 160, characters 24-27:
160 |       String.unsafe_set str n (f (String.unsafe_get str n))
                              ^^^
Error: This expression has type string but an expression was expected of type
         bytes
```

ocaml-4.12
FreeBSD 13

**Comment by kit-ty-kate** [comment]
How did you get this with opam? The package requires OCaml < 4.06 so it shouldn't be possible to compile on OCaml 4.12.
Trying to guess what's going on, is this about https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250408 ?

If so, it doesn't looks like this library is still maintained but just in case it is you can contact the original author if they want to port it, though given the webpage for this project (http://raevnos.pennmush.org/code/annexlib/index.html) hasn't been updated since 2006 I doubt that would be the case.

I can have a go at it, but I'm rather busy with other things I would most likely change the library significantly enough that it would diverge greatly from upstream. Is there any protocol in FreeBSD to remove such old packages?

**Comment by kit-ty-kate** [comment]
I'm guessing this was fixed by https://github.com/freebsd/freebsd-ports/commit/4f4912744b7930e00a1ccf46c508d88b16806ea8 ?
