### ISSUE TITLE
two CI runs failing to install camlbuild.0.14.2+win

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#23954]
FYI, here are two CI runs failing to install camlbuild.0.14.2+win
https://github.com/ocsigen/js_of_ocaml/actions/runs/5310258265/jobs/9611988249?pr=1471
https://github.com/ocaml-multicore/domain-local-timeout/actions/runs/5298966353/jobs/9591634270

_Originally posted by @hhugo in https://github.com/ocaml/opam-repository/issues/23832#issuecomment-1596925543_

**Comment by talex5** [comment]
It's still failing for me in CI (but works locally). Oddly, opam first says it *did* download it, then that it failed:
```
[ocamlbuild.0.14.2+win] downloaded from https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.2.tar.gz
...
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocamlbuild.0.14.2+win
```

**Comment by maroneze** [comment]
I tried installing `frama-c.27.0`, and the three following packages failed:

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - frama-c.27.0
          - ocamlbuild.0.14.2+win
          - why3.1.6.0
```

With `opam install --debug`, we see the files are downloaded, then I have something similar to `C:\OCaml64\bin\tar.exe xfz /home/user/.opam/download-cache/md5/2f/2f407fadd57b073155a6aead887d9676`, which I assume fails, then opam removes the temporary directory and reports a failure.

In every case, running the same command manually results in decompression of all files, except the ones which are symbolic links. These result in error messages (in the case of `ocamlbuild.0.14.2+win`, that's `examples/07-dependent-projects/libdemo`, which causes a `Cannot change mode to rwxr-xr-x: Not a directory`), which result in `tar` returning a non-zero value.

The behavior must have changed from before, since I'm almost sure there were already archives containing symbolic links which nevertheless seemed to work with Cygwin.

**Comment by SamChou19815** [comment]
This is also affecting Flow: https://app.circleci.com/pipelines/github/facebook/flow/6193/workflows/78876806-7a05-49cc-a116-d8200aa6ada3/jobs/109226

**Comment by dra27** [comment]
Just to report that the issue is Cygwin 3.4.7 (released 16 June). I'll report back with an actual workaround...

**Comment by dra27** [comment]
@maroneze - thanks for the investigation and the symlinks observation, which made searching the Cygwin mailing list that bit quicker!

**Comment by dra27** [comment]
setup-ocaml 2.0.17 works around the issue, and in fact the Cygwin tar package has already been updated (as with other distros, mirrors can take a little while to sync), so by Monday it should be possible to revert the workaround in 2.0.17 💨
