### ISSUE TITLE
package lz4 and depext

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#4076]
I am on Ubuntu 14.04.2 LTS, opam 1.2.1.
If I do 'opam depext lz4', it apparently tries to install something
from sources instead of installing the system package liblz4-dev.
I think that's a bug.
It does so even if the mentioned package is already installed on my system.

**Comment by AltGr** [comment]
according to the semantics of depext flags, both should be done ; and we have no way to detect that a script has already been run, so it will be re-run every time:

```
depexts: [
  [["debian"] ["liblz4-dev"]]
  [
    ["source"]
    [
      "https://gist.githubusercontent.com/whitequark/eef074a8daa14602e447/raw/c151d3ab2f35f6cac54c7ef7459e2bbfff852938/install.sh"
    ]
  ]
  [["ubuntu"] ["liblz4-dev"]]
]
```

for each pair (tags, target), target should be installed whenever tags is a subset of the system's current tags. `"source"` is ignored in these checks, and triggers download+execution of the given target instead of installation as a system package.

So here, the gist `install.sh` will be run whenever, whatever the system.
These "source" depexts should go away. Could a solution be to make them opam packages with a "script" tag ? (there might be way to have packages installing interactively un 1.3, which could permit sudo).

**Comment by UnixJunkie** [comment]
I am afraid the packager meant by "source": anything else than the distros listed on other lines.
I.e. if not ubuntu and not debian then use the source-based installer.
@whitequark  am I right ?

**Comment by whitequark** [comment]
Yeah. I'm fairly sure it selected the first matching one before. Either way, this is the proper behavior in my opinion and it should be restored...

**Comment by UnixJunkie** [comment]
maybe a better tag name for the opam file would be "other": "source" is not the name of any operating system I know of

**Comment by UnixJunkie** [comment]
maybe a temporary quick fix is to put "source" as the last line in the depexts section

**Comment by AltGr** [comment]
the contents of the `depext:` fields is stored in a map, and I think it always was so, so ordering is irrelevent. The semantics is a bit weird, granted, but I followed what was in place (not to change the semantics and the code at the same time!)

The `"source"` depext needs to go anyway: it's too unsecure and not well defined (I found one that did `add-apt-repository` -- on debian, which doesn't have it by default -- for example). But we don't have a suitable workaround yet...

**Comment by paurkedal** [comment]
Printing out instructions about how to satisfy the dependency manually seems like a reasonable workaround when the automatic solution is too intrusive or unsafe.

**Comment by UnixJunkie** [comment]
if the security of opam is to be increased, then I would flag this problem as a security bug

**Comment by dbuenzli** [comment]
Discussion on this issue seems to have diverged. The broader issue about depexts should be discussed on the depext [issue tracker](https://github.com/ocaml/opam-depext/issues) and in [this opam issue](https://github.com/ocaml/opam/issues/2919).

Regarding the original issue version `1.1.0` and `1.1.1` no longer have the `source` depext so this should be solved. If anyone wants to remove the `source` dependency from version `1.0.0` and `1.0.1` is welcome to open a PR.
