### ISSUE TITLE
Force package submitters to include examples

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam-repository#5449]
OCaml is notorious for lacking of examples or documentation. 

Since opam maintainers are already doing a sort of curation, giving pointers or requests about compiler version, presumably for the good of the community then I propose that inclusion of self contained examples including build instructions be a prereq for submitting to opam.

**Comment by dsheets** [comment]
The difficulty of providing accurate constraints in opam metadata (so that packages work on the systems they are specified for and don't work on the systems that are excluded) is much less onerous than the difficulty of writing examples or documentation. It's my understanding that we can't really demand that packagers, authors, or maintainers include more or different *content* in their packages but it is good for the community and users of the opam repository for the metadata stored in the repository to be up-to-date. If users find out-of-date or incorrect metadata in package descriptions, we are happy to merge updates to those metadata. I believe the repository maintainers' role is to ensure quality and accuracy of the metadata held in the repository rather than to exercise editorial or selective bias as a museum curator would.

Examples and documentation locations can be specified in opam metadata via the `homepage` and `doc` fields.

As always, finding the right balance between requirements for packagers and ease of publication is a trade-off. I think we would all like to see the opam repository full of packages with complete documentation, examples, international localizations, and compatibility with the latest versions of dependencies. Unfortunately, if we were to reject packages without those traits, we would have an order of magnitude fewer packages to offer users and developers.

Do you have any ideas about how we can encourage packagers to improve their documentation and examples? For a while, a group of us were discussing using [opam.ocaml.org](https://opam.ocaml.org/) to highlight packages which had good documention or were "well-maintained" but these features are tricky to get right and potentially damaging and unfair to packagers which don't have the time or inclination to fit into whatever heuristic we might invent. There is probably a way to accomplish the surfacing, integration, and discovery of rich packages that doesn't have these issues, though. I would suggest getting involved with the [opam2web](https://github.com/ocaml/opam2web) project if you'd like to contribute to this effort.

**Comment by dsheets** [comment]
Regarding compiler version requests, the PR #5430 is a recent example of repository metadata quality assurance.

**Comment by dbuenzli** [comment]
@fxfactorial The right move here is to complain upstream for the packages you care about and not use those that don't have the qualities you think are needed. 

The main `opam-repository` should be about consistent package delivery and traceabilty (i.e. good metadata), not about package contents --- except for malicious activity.

Package curation is always going to be extremely contentious and unlikely to be frictionless. Forcing this on the entry point of the OCaml ecosystem would result in a less welcoming environment. Curation should be left to specialized repositories maintained by persons who have the time and energy to do so. Personally I'm not sure I'd be interested in those either, I don't mind the bazaar.

That being said I and others are still working on tools that will ease and enforce better practices at the package developer level, which if used will result in better package quality without having to enforce anything at the `opam-repository` level.

**Comment by fxfactorial** [comment]
Much of this is simply a difference of opinion.

@dsheets.

1) It is easier for me and presumably other programmers to write
example code that uses the very code I wrote rather than memorize the
million little rules of opam.

2) Would opam really just blindly accept a package for a program that
say creates a map that shows where Jews are so that its easier for bad
people to target them? Or an opam pacakge that DDoSes gay websites.

You can say they are absurd examples and write this off but that's
probably because the # of packages is small and we haven't encountered
yet crazies or corner cases.

3) Have an order of magntitude fewer? If people took the time to write
their code AND took the time to submit it to a central package
repository, then they should take the time to provide examples rather
than use opam as a dumping ground. Why not sell opam as a place of
quality rather than quanitity, it already is just 1200 package, a tiny
fraction of that npm provides.

4) My idea for making people improve is to force them to include
examples. From you last paragraph I effectively read

"We didn't know how to do it without potentially upsetting some
people, therefore we just didn't do it."

Getting your package on opam feels good, its a currency. Why wouldn't
it also be a currency, a good feeling to have your package be the
highlighted package of the week for good examples/documentation (Maybe
that's a way right there)

@dbuenzli

And when upstream doesn't care, ignores then you would say what,
"That's life?". Upstream often times can't even be bothered to fix
trivial mistakes, EVEN when the fix is provided!

https://github.com/savonet/ocaml-ssl/issues/22

You know what's an unwelcoming environment? When you're just starting
with a language, don't understand any of the five build tools and have
no idea how to compile or run any of the code, that's unwelcoming.

<not_sarcasm> Great programmers like you don't mind the bazaar, but
I'm not on your level yet and I need examples of code before I just
instantly grok it and being told "Just read the source derpa derp" is
almost as useless for me, Lwt anyone? </not_sarcasm>

opam is small right now, we have a chance to make it a place that is
practical welcoming, instead we are afraid of losing some theoretical
packages, authors. I guess the goal is to become npm, with 300k
packages.

**Comment by dbuenzli** [comment]
> You know what's an unwelcoming environment? When you're just starting
> with a language, don't understand any of the five build tools and have
> no idea how to compile or run any of the code, that's unwelcoming.

This is not the problem of `opam-repository`, this is the problem of the environment itself and introductory material to the environment (e.g. it would have been nice if RWO would have been able to get out of its JS `core` closed world assumption and had --- rather than provide its own wrapper around ocamlbuild and thus introducing even more noise in the system --- included an introduction to ocamlfind and ocamlbuild, a beginner friendly build system). 

> programmers like you don't mind the bazaar, but

Don't misunderstand me. When I say I don't mind the bazar I mean: I don't mind if there are packages of different quality. I do care a lot about the usability of the whole system, if only for myself.

However I don't think that what you propose here is able to greatly improve the usability of the system. Given a build system, learning how to link a package and diagnose link errors is mostly a pattern that you need to learn in introductory material to the environment or to the build system itself.

As for sample code this is something that should be left at the discretion of the package developers. Some of my packages do have sample code and build instructions, other don't according to the triviality of the API/subpackage setup. I don't think it's a good idea to start asking `opam-repository` maintainers to judge this (even more so that there would be no UI at the moment for doing this). 

Finally remember that the human forces involved behind all this are also quite limited, so we need to be able to rely on the package authors' responsability or their users reminding them --- in other words I think that it is good if responsabilities are modularized.

**Comment by fxfactorial** [comment]
@dbuenzli 

How about this, yes, I agree that this is the problem of the environment itself, but let's what if `opam` we say that opam is a chokepoint where we can throttle entry of good packages. Haskell's hackage is well known for being well filled with crappy packages that don't even build with each other, hence stackage was made.

What if we had a switch for opam that was only filled with packages that did include examples, documentation. We could incentivize people with praise and extra exposure on opam/ocaml web page that did post their packages to this switch.

**Comment by dbuenzli** [comment]
> What if we had a switch for opam that was only filled with packages that did include examples, documentation. We could incentivize people with praise and extra exposure on opam/ocaml web page that did post their packages to this switch.

From an opam point of view this would not be a switch but rather a repository. The system is open, do start such an initiative if you feel it's missing, maybe you can even convince people running the opam  or ocaml website to give exposure to it. 

But then I'd just like to point that it's not because a package has examples and documentation that it means that its API is well designed, scales and is bug free. So with respect to this I again much prefer the bazaar where random shit is published and eventually selected by users than having `opam-repository` maintainers defining arbitrary rules for what is allowed to get in the system.

**Comment by fxfactorial** [comment]
@dbuenzli 

Fine, I see your point. The cynic in me wants to say that this is a punt on the issue of examples, documentation. I suppose I could be a gadfly to people, 

https://github.com/mirage/mirage-profile/issues/15

Its pretty clear, this is a cultural issue, there no technical solution at all apparently.

**Comment by michipili** [comment]
I personally provide examples for all the OCaml code I write, either in the form of plain examples or of test-cases. (see my GH account, e.g. [lemonade](https://github.com/michipili/lemonade/tree/master/testsuite) or [gasoline](https://github.com/michipili/gasoline/tree/master/example))  I would wish to see more of them, but I am not sure about enforcing rules (it is hard to find good rules and rules have to be verified, which is also extra work).

As others pointed out (@gasche in reddit IIRC) providing examples is also a great way to help with open source projects.
