### ISSUE TITLE
Package dependency between upstream repositories

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam-repository#5484]
Is it possible to say that a package from repository A has a dependency on a package from repository B?

**Comment by dsheets** [comment]
This is not possible currently as far as I know.

You may be interested in the `repo` file <https://github.com/ocaml/opam-repository/blob/master/repo> which lets repository maintainers declare repository-wide metadata. This file could conceivably be extended with information about related repositories that the user's agent should use in order to resolve package names.

I recommend filing issues at https://github.com/ocaml/opam/issues for this and related features as this does not concern the operation of this repository as far as I can tell.

**Comment by fxfactorial** [comment]
appreciated, sorry bout noise.
