### ISSUE TITLE
aws: name clash!

### ISSUE THREAD

**Issue by pwbs** [ocaml/opam-repository#5619]
The 2 packages <https://opam.ocaml.org/packages/aws/aws.0.0.3/> and <https://opam.ocaml.org/packages/aws/aws.0.1.0/> have nothing in common except the name!

It's causing some awkward trouble in some places...

**Comment by pwbs** [comment]
Please @seliopou could you rename your package? To ocaml-aws perhaps?

**Comment by avsm** [comment]
Is this causing a problem from things depending on aws.0.1.0? The intention was to deprecate the old one with the much more complete aws.0.0.3.

**Comment by dsheets** [comment]
`aws.0.0.3` is besport's package and `aws.0.1.0` is @seliopou's recently released package.

**Comment by pwbs** [comment]
aws.0.0.3 is the one we're currently using at besport, aws.0.1.0 is a different thing, with apparently no common commits...

**Comment by amirmc** [comment]
It looks like it's causing a problem in multiple places.  The pages linked above imply that `aws.0.1.0` is a newest version of `aws`.

**Comment by amirmc** [comment]
... which would also imply that anyone doing an `opam update` might not get what they expected. @pwbs  is this what you're seeing?

In a more general sense, would it be possible to add something to the lint so that name clashes are revealed in the PR?  That might have surfaced the issue before merge in https://github.com/ocaml/opam-repository/pull/5581

**Comment by pwbs** [comment]
Apparently, from what I understand from https://github.com/ocaml/opam-repository/pull/5581, the intention was to deprecate 0.0.3., with however a completely different interface and way of doing things.
I can understand that the intention was good. However the result is not.

Perhaps https://github.com/besport/aws/, on which 0.0.3 is based, should die, I don't know, but not like this anyways. It's wrong to come with https://github.com/inhabitedtype/ocaml-aws/ and claim that the former shouldn't exist anymore (yes, that's what it's saying by using 0.1.0, because what version number shall be given to the version following 0.0.3 if it didn't cease to exist?). I personally don't care if it's the old aws that gets to be renamed or the new one, but clearly they shouldn't share the same name, it's confusing, misleading and wrong.

**Comment by seliopou** [comment]
A little background on the change. Inhabited Type started developing an AWS library about a year ago around the idea of generating libraries for each individual service, based on service descriptions published by the boot library. Taking this approach, OCaml will have support not just for EC2 and S3, but for *every* service Amazon provides.

Several months ago we decided to open-source the project so that others could benefit from it. At the time we reached out the original authors and asked if it would be OK to take over the AWS namespace with the core library and additional libraries for each service (aws-ec2, aws-s3, etc.). They agreed, and we moved forward, though slowly. The latest release is the first step in transitioning to auto generated libraries for all the services. (I'm working on a pull request to release all the generated libraries so far.) This is mostly to say that I did not act unilaterally, but discussed it with the stakeholders that I knew of before moving forward. Having said that, we should have tried to get the word out to users as well. Having said that, we should have tried harder to get the word out to users as well, but we did try (see below).

That's the background. Now to the conflict between the previous and latest versions of the libraries. Before releasing, I did a cursory search of opam for libraries that depended on aws and found none. Had I found any, I would have informed the project and suggested they add a version constraint to ensure that the new library was not installed during an upgrade. I chose `0.1.0` because it makes sense with respect to semantic versioning, while also allowing for additional releases of the original library if the need arose (e.g., `0.0.4`, `0.0.5`, etc). It's seems to me that the source or provenance of the API being exported by a package only matters to the extent that changes in source or provenance change the API, at which point it becomes a matter of versioning appropriately, rather than naming appropriately. Put another way, versions are there for APIs rather than codebases. I think releasing the new library under the same version, or just bumping the patch version, would have been unjustifiable and confusing, never,ind bizarre. Introducing a new API and bumping the minor version while the major version is still `0` seems like the sensible and workable thing to do.

**Comment by pwbs** [comment]
I don't have an opam package that depends on `aws`, but I do have an application that uses it and that will never get into opam (because it wouldn't make sense if it ever did). Assuming that looking at other opam packages to know if it's okay to do such a thing is like assuming that *opam packages are only useful for building other opam packages*... o_O
To me, it doesn't make sense to have 2 libraries that are so different and that have the same name.

> I think releasing the new library under the same version, or just bumping the patch version, would have been unjustifiable and confusing, never,ind bizarre. Introducing a new API and bumping the minor version while the major version is still 0 seems like the sensible and workable thing to do.

First, but it's just my opinion, your reasoning is not bad however built on wrong grounds: I mean, `0.0.3` is wrong and it's not your fault. 0.0.x should be only for things that are very unstable and/or barely usable.

Second, since the new interface has exactly nothing to do with the old one, I believe you should have at least bumped the most major number, which would mean 1.0.0, and if 1.0.0 is too bizarre, then choose 2.0.0 because then it would have been extremely clear that the compatibility was be completely broken. 

Now, I feel that I've wasted too much time already with this issue... and I'm afraid this error will repeat at some point. 

And I apologies in advance for this: I'm now stopping to care about what happens next.

**Comment by lefessan** [comment]
Is anybody still maintaining aws 0.0.3 ? It makes sense to have a new aws project taking over (but indeed, a bump to 1.0 or 2.0 would show the incompatibility).

**Comment by avsm** [comment]
a bump to 1.0 does indeed make sense. The upstream author of aws.0.0.3 has indicated that they are no longer maintaining it and are fine with this namespace swap.

**Comment by lefessan** [comment]
If there is no opposition, I will rename aws.0.0.3 to aws.1.0.0 tomorrow, unless @seliopou wants to do it himself.

**Comment by pwbs** [comment]
@lefessan didn't you mean "rename aws.0.1.0 to aws.1.0.0"?

**Comment by seliopou** [comment]
If it satisfies all parties, I'll go with the version change. Would you like a separate release?

**Comment by lefessan** [comment]
Oups, thanks Philippe, yes, I meant 0.1.0 to 1.0.0 !

**Comment by lefessan** [comment]
@seliopou: you should probably indeed modify the archive internally to show version 1.0, so a separate release would make sense (and the PR to opam-repository should remove 0.1.0 at the same time).
