### ISSUE TITLE
list of packages without upstream archive

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam-repository#5684]
Hi,

  I have started to run a daemon to check the "downloadability" of OPAM packages. The results are here:

http://opam.ocamlpro.com/issues/

  The daemon also backups archives, so it will be possible to retrieve them when their links become dead:

http://opam.ocamlpro.com/backup/

--Fabrice

**Comment by avsm** [comment]
This is really useful! I have a couple of things that might help:

- an [opam-mirror](https://github.com/avsm/opam-mirror) tool that downloads archives -- the plan was to put this into Irmin to be tracked as git blobs.  @AltGr is there an opam issue around having multiple fallback URLs, so that we can point to a central server that serves as a backup mirror?  

- an experimental regular Docker Hub opam-archive build that downloads everything into a local container that serves via HTTP: https://hub.docker.com/r/ocaml/opam-archive -- still working on documenting this, but it could also publish the failure logs from opam-admin make somewhere

**Comment by dbuenzli** [comment]
Half a year later, what do we want to do with this ?

**Comment by dbuenzli** [comment]
This issue is lacking a concrete action plan so I'm closing this. If someone has a concrete plan, he should open a new issue with a precise plan on how to get this in the repo in a timely manner.
