### ISSUE TITLE
camlp5-transitional

### ISSUE THREAD

**Issue by ksk** [ocaml/opam-repository#659]
In opam, camlp5 is installed as strict mode by default.
Is there any way to install camlp5 as transitional mode through opam?

**Comment by catalin-hritcu** [comment]
Same question here. Need this to compile some old version of Coq:
```
[hritcu@detained coq-8.1pl6]$ ./configure --local   
You have Objective-Caml 3.12.1. Good!
You have native-code compilation. Good!
Error: Camlp5 found, but in strict mode!
Please compile Camlp5 in transitional mode.
```

**Comment by catalin-hritcu** [comment]
Finally I managed to get a transitional version of camlp5 6.04 that together with ocaml 3.12.1 can build Coq 8.1 and 8.2 from source. The process was rather complicated (and involved even more trial and error):
- Got a local version of opam repo:
```
git clone https://github.com/ocaml/opam-repository.git
opam repository add local opam-repository
```
- Created an alias of ocaml 3.12.1 so that I don't ruin any of my switches
```
opam switch install 3.12.1-old-camlp5 --alias-of 3.12.1
```
- Edited the opam package for camlp5 6.04 to add the `-transitional` flag to `./configure`
```
emacs opam-repository/packages/camlp5/camlp5.6.04/opam
```
- Removed the `default` repo (this seems shady, but without this opam kept installing the remote package when specifying a version)
```
opam repo remove default
```
- Installed camlp5 6.04
```
opam install camlp5.6.04
```
- With this could finally compile Coq:
```
./configure --local -camlp5dir /home/hritcu/.opam/3.12.1-old-camlp5/lib/camlp5
make -j world
```
- Added back the default repo (to revert previous shady change)
```
opam repo add default https://opam.ocaml.org/ --priority 0
```

@gasche Do you know an easier way to do this? :)

**Comment by gasche** [comment]
You could indeed simplify the process quite a lot by using the `opam pin` mechanism, whose purpose is to let you override the global-repo packages with a specific local version of a package. See the [opam pin](https://opam.ocaml.org/blog/opam-1-2-pin/) documentation for instructions -- the global idea is to clone the package locally, to give it (or edit if it exists) an `./opam` file with configuration, pin that local version, and ask opam to upgrade the package.

For the question of how to enable that "transitional" mode without pinning, well we could either propose two different packages in the repository (marking them as conflicting with each other, if `transitional` is a global configure-time flag and it makes no sense to have some packages relying on it and some other not), or keeping a single package but with a boolean `camlp5:transitional` configuration variable to let user choose. I am not very familiar with the handling of package variables in OPAM (how would a Coq-8.1 package depend on "camlp5 with `camlp5:transitional` enabled?", nor is the [the manual](https://opam.ocaml.org/doc/Manual.html#Variables) explicit enough about it, so we would need to ask an OPAM expert.

**Comment by gasche** [comment]
Do you expect to still actively need access older Coq versions in the future? Because we might want to try patching those old Coq versions to work on newer OCaml releases, I would expect it not to be a lot of work.

**Comment by gasche** [comment]
Thinking of it more, I think using package variables is not a good fit for `-transitional`, because arbitrary packages that rely on camlp5 today may not work anymore if `-transitional` is enabled (so we would have to specify in every dependency of `camlp5` whether the dependency expect `camlp5:transitional` to be true or false). It is probably better to have a specific package `camlp5-transitional`, that would conflict with the usual `camlp5` package.

Another option would be to package and use an older camlp5 version, before the `transitional` split. @catalin-hritcu , do you have a specific reason to have chosen this camlp5 version instead of an older one?

**Comment by catalin-hritcu** [comment]
> You could indeed simplify the process quite a lot by using the opam pin mechanism, whose purpose is to let you override the global-repo packages with a specific local version of a package. See the opam pin documentation for instructions -- the global idea is to clone the package locally, to give it (or edit if it exists) an ./opam file with configuration, pin that local version, and ask opam to upgrade the package.

I didn't manage to get `opam pin` to work in this case. I could pin a specific version (6.04), but then the opam package for that version was taken from the `default` repo, although I had a higher priority `local` repo with my changes. I also tried to pin a path, but I have no clue what opam expects to find at that path. When passed `../opam-repository/packages/camlp5/camlp5.6.04/` as a path (the place where my changed version of the opam package was sitting) `opam install campl5` failed because apparently it couldn't find the `configure` script, but it was looking for it in a temporary dir containing a copy of `../opam-repository/packages/camlp5/camlp5.6.04/`, so of course it wasn't finding it there.

> do you have a specific reason to have chosen this camlp5 version instead of an older one?

It was the oldest version of camlp5 for which the `opam-repository` has a package. Initially I tried the latest version of camlp5, and actually compiling a transitional version of that was easier, since I didn't need to pin a version, and my changes to the `local` repo worked just fine. The Coq compilation for both 8.1 and 8.2 failed with the latest camlp5 version though, so afterwards I went for the oldest version I could find in `opam-repository`.

> Do you expect to still actively need access older Coq versions in the future? Because we might want to try patching those old Coq versions to work on newer OCaml releases, I would expect it not to be a lot of work.

Yes, and I think I'm not the only one who regularly uses developments that need older versions of Coq. Unfortunately, I'm not an OCaml expert and I already killed too much time on this last night, so I don't think I would be able to help much at this point.

@maximedenes  Any thoughts on this?

**Comment by gasche** [comment]
So here are the steps I used, adapting your workflow to use `pin`. I'm using opam 1.2.0.

1. Download the [archive](http://camlp5.gforge.inria.fr/distrib/src/camlp5-6.04.tgz) of Camlp5 6.04 and extract it somewhere (`/tmp/camlp5` in my case). Use a 3.12.1 opam switch.

2. Copy the `opam` file of the opam-repository for this camlp5 version in the camlp5 source directory (`/tmp/camlp5`). Edit it to add the line `version: "6.04"` (otherwise pinning will wrongly assume it is the latest package version) and `"--transitional"` as extra configuration option.

3. From `/tmp/camlp5`, run `opam pin add camlp5 .`. This will install this local copy of camlp5 in the switch.

4. Compile the coq archives. I used `./configure --local --camlp5dir $(ocamlfind query camlp5)`, because without this `--camlp5dir` option.

I'm not actually sure that this works, because the compilation of Coq 8.1pl6 fails with an error down the line on my machine.

```
File "pretyping/pretype_errors.ml", line 43, characters 4-109:
Error: Unbound constructor Stdpp.Exc_located
```

**Comment by catalin-hritcu** [comment]
Thanks a lot for the better instructions. I was indeed not merging the archive with the opam package as you did in steps 1 and 2. Indeed you need the explicit `camlp5dir` option for compiling Coq 8.1 or 8.2, since the camlp5/4 detection code in the `configure` script seems in many ways broken. At first I tried to fix it, but that was a pain since things kept failing. So did you manage to compile Coq by passing the `camlp5dir` option, or was the last failure even with that option?

**Comment by gasche** [comment]
The last failure was even with that option, but I don't know anything about this codebase so I couldn't tell if this was camlp5-related. Is it?

**Comment by catalin-hritcu** [comment]
My impression is that it's indeed a campl5 related error, caused by some sort of mis-configuration of confusion with camlp4. I was also getting this error at some point during my many failed attempts. Please do a `make clean` and even `make archclean` and try again. Also please double check that the camlp5 in your path is indeed transitional with `camlp5 -pmode`  I'll let you know if I remember anything else :)

**Comment by catalin-hritcu** [comment]
Well ... the obvious one, check that you're using the old ocaml version too (3.12.1).

**Comment by gasche** [comment]
All this was correct, but I had a look at the failure: Std_pp.Exc_located is indeed defined in Camlp5, but it does not exist anymore with the version 6.04. I re-did the exact same step with version 5.15 and 6.03 (the last versions with Std_pp.Exc_located), and then Coq 8.1pl6 builds without errors in both cases.

**Comment by catalin-hritcu** [comment]
Glad that it finally worked. The strange part is that I can still successfully build Coq 8.1pl6 with Camlp5 version 6.04. I've tried again with clean Coq 8.1pl6 sources to make sure I don't have any local fixes. One thing that I did different from you is that I didn't use `ocamlfind` (I don't have it installed at all in my switch). Here is the `configure` information:

```
[hritcu@detained coq-8.1pl6]$ ocaml -version
The Objective Caml toplevel, version 3.12.1
Use option -help for usage
[hritcu@detained coq-8.1pl6]$ camlp5 -v       
Camlp5 version 6.04 (ocaml 3.12.1)
[hritcu@detained coq-8.1pl6]$ camlp5 -camlp5 -pmode
transitional
[hritcu@detained coq-8.1pl6]$ ocamlfind query camlp5  
zsh: command not found: ocamlfind
[hritcu@detained coq-8.1pl6]$ ./configure --local --camlp5dir /home/hritcu/.opam/3.12.1-old-camlp5/lib/camlp5
You have Objective-Caml 3.12.1. Good!
You have native-code compilation. Good!
LablGtk2 not found: CoqIde will not be available.

  Coq top directory                 : /home/hritcu/Temp/coq-8.1pl6
  Architecture                      : Linux
  OS dependent libraries            : -cclib -lunix
  Objective-Caml/Camlp4 version     : 3.12.1
  Objective-Caml/Camlp4 binaries in : /home/hritcu/.opam/3.12.1-old-camlp5/bin
  Objective-Caml library in         : /home/hritcu/.opam/3.12.1-old-camlp5/lib/ocaml
  Camlp4 library in                 : /home/hritcu/.opam/3.12.1-old-camlp5/lib/camlp5
  FSets theory                      : All
  Reals theory                      : All
  CoqIde                            : no

  Paths for true installation:
    binaries   will be copied in /home/hritcu/Temp/coq-8.1pl6/bin
    library    will be copied in /home/hritcu/Temp/coq-8.1pl6
    man pages  will be copied in /home/hritcu/Temp/coq-8.1pl6/man
    emacs mode will be copied in /home/hritcu/Temp/coq-8.1pl6/tools/emacs

If anything in the above is wrong, please restart './configure'

*Warning* To compile the system for a new architecture
          don't forget to do a 'make archclean' before './configure'.
[hritcu@detained coq-8.1pl6]$ make world
rm -f .depend.camlp4
for f in tactics/tauto.ml4 tactics/eqdecide.ml4 tactics/extraargs.ml4 tactics/extratactics.ml4 tactics/eauto.ml4 toplevel/whelp.ml4 tactics/hipattern.ml4 contrib/omega/g_omega.ml4 contrib/romega/g_romega.ml4 contrib/ring/g_quote.ml4 contrib/ring/g_ring.ml4 contrib/dp/g_dp.ml4 contrib/setoid_ring/newring.ml4 contrib/field/field.ml4 contrib/fourier/g_fourier.ml4 contrib/extraction/g_extraction.ml4 contrib/xml/xmlentries.ml4 contrib/jprover/jprover.ml4 contrib/cc/g_congruence.ml4 contrib/funind/tacinv.ml4 contrib/first-order/g_ground.ml4 contrib/subtac/g_subtac.ml4 contrib/subtac/g_eterm.ml4 contrib/rtauto/g_rtauto.ml4 contrib/recdef/recdef.ml4 contrib/funind/indfun_main.ml4  contrib/interface/debug_tac.ml4 contrib/interface/centaur.ml4 parsing/lexer.ml4 parsing/pcoq.ml4 parsing/q_util.ml4 parsing/q_coqast.ml4 parsing/g_prim.ml4  parsing/g_minicoq.ml4 parsing/g_vernac.ml4 parsing/g_proofs.ml4 parsing/g_xml.ml4 parsing/g_constr.ml4 parsing/g_tactic.ml4 parsing/g_ltac.ml4 parsing/argextend.ml4 parsing/tacextend.ml4 parsing/vernacextend.ml4 parsing/q_constr.ml4 parsing/g_decl_mode.ml4 toplevel/mltop.ml4 lib/pp.ml4 lib/compat.ml4 contrib/xml/xml.ml4 contrib/xml/acic2Xml.ml4 contrib/xml/proofTree2Xml.ml4 contrib/interface/line_parser.ml4 tools/coq_makefile.ml4 tools/coq-tex.ml4; do \
  printf "%s" `dirname $f`/`basename $f .ml4`".ml: " >> .depend.camlp4; \
  echo `sed -n -e 's|^(\*.*camlp4deps: "\(.*\)".*\*)|\1|p' $f` >> .depend.camlp4; \
done
[...]
```
I've included the rest if the `make world` output in here:
https://gist.github.com/catalin-hritcu/e82add4a51492f8d0a97

**Comment by gasche** [comment]
Indeed: it seems I made a mistake somehow, `Exc_located` is still part of 6.04, it was only removed in 6.05. I must have wrongly renamed something. Sorry for the confusion.

**Comment by lefessan** [comment]
Here is an idea:
* we could add a `conf-camlp5-transitional` package to the repository (empty package)
* camlp5 would have a `depopt` on that package. if `conf-camlp5-transitional` is installed, then `camlp5` would compile in transitional mode instead of strict. Packages that requires transitional mode would depend on `conf-camlp5-transitional`, while packages that require strict mode would declare a conflict with it.

Would it solve the issue ?

**Comment by catalin-hritcu** [comment]
@gasche is the expert, so maybe he can answer on the technical question.

In the meanwhile, Hugo Herbelin (@herbelin) fixed the old branches of Coq (e.g. https://github.com/coq/coq/tree/v8.1) so that they all work well with opam and the normal (non-transitional) version of camlp5. So now that Coq users can install old version of Coq from opam without problems, maybe nobody needs camlp5-transitional?

**Comment by lefessan** [comment]
It seems that HOL had the same problem.

**Comment by dbuenzli** [comment]
> So now that Coq users can install old version of Coq from opam without problems, maybe nobody needs camlp5-transitional?

If that is the case then I think this can be closed.
