### ISSUE TITLE
Coqide 8.5.1 and OCaml 4.03

### ISSUE THREAD

**Issue by gares** [ocaml/opam-repository#6849]
Coqide specifies no dependency on OCaml but it fails to build with 4.03.

**Comment by gasche** [comment]
@gares I think for this kind of issues it's best to send a pull-request directly if you know what to do.

If there is a fundamental reason why coqide itself is incompatible with 4.03 (the package itself is broken by a change of semantics somehow), it makes sense to add a version bound (`available: [ocaml-version < "4.03"]`) to the package -- you can send a PR to fix that package metadata directly. 

I'm trying to build coqide to try right now (but building coq takes ages...), but I would hazard the guess that the failure is rather something else in the dependency chain that does not work with 4.03. In that case, try to add a bound on this dependency or fix the underlying issue -- it may not be very hard.

**Comment by gasche** [comment]
So the error message is as follows:

```
# File "lib/xml_lexer.cmo", line 1:
# Warning 31: files lib/xml_lexer.cmo and lib/clib.cma(Xml_lexer) both define a module named Xml_lexer
# File "lib/xml_parser.cmo", line 1:
# Warning 31: files lib/xml_parser.cmo and lib/clib.cma(Xml_parser) both define a module named Xml_parser
# File "lib/xml_printer.cmo", line 1:
# Warning 31: files lib/xml_printer.cmo and lib/clib.cma(Xml_printer) both define a module named Xml_printer
# File "ide/coqide_main.ml4", line 1:
# Error: Some fatal warnings were triggered (3 occurrences)
# make[1]: *** [bin/coqide.byte] Error 2
# make: *** [submake] Error 2
```

It would be nice if we could just disable warning-as-errors in the distributed version of this package.

**Comment by gares** [comment]
Unfortunately I don't know what to do.  My personal opinion is that the OPAM model is not helping.  If I think at it as a way to distribute Coq, then I want to say OCaml=the-version-I-tested-it-on.   But if I think at OPAM a tool for OCaml developers, then I'm happy with a loose dependency, so that you can use Coq on any OCaml version that happens to work, more importantly you can test Coq on any OCaml branch.

In the past I've advocated putting the Coq package in the Coq specific OPAM repository, to avoid random users (i.e. it wasn't me discovering the problem) to end up in a situation they are not able to solve.  Would that be acceptable from the opam-repository POV?  IIRC there are packages depending on Coq, but that are not Coq specific.  So they would end up with a (maybe optional) dependency on non-existing packages.

**Comment by gasche** [comment]
In fact my analysis of the issue above was wrong, it's not really Coqide's responsibility: there was a change of behavior where double-linking is now treated as an error by default in 4.03, while it was just a warning before. So that's a case of actual version incompability -- that would best be fixed.

Regarding the larger question of whether Coq should be packaged in the ocaml repository instead of just the coq-specific repositories, I don't have an opinion myself. I do find installing coq through the ocaml repository inconvenient (it makes me very angry when I install a different camlp5 version for the purposes of Coq development and it tries to rebuild the opam-installed Coq), but it can be convenient for end-users on a distribution that doesn't have Coq packaged.

I think the current statu-quo is not that bad: it mostly work, and when it doesn't people complain and you have stuff to fix. But in this instance for example, it would indeed be the responsibility of the Coq community to fix it -- with advice from upstream OCaml experts that know about the differences of 4.03 for example. In general it would be nice if the Coq team had enough time, before a new OCaml release, to test that Coq works properly with the new version and perform the necessary fixes otherwise -- this requires good will of the Coq team, a de-ossified process of not just using the old-stable Debian OCaml version, and I think you've made lots of progress on that thanks to opam, Emilio etc., and probably also better guidance from OCaml upstream about how to upgrade and maybe more testing time before each release.

You should probably get in contact with the why3 people, they are the main dependency on Coq in opam ( see [the dependencies here](https://opam.ocaml.org/packages/coq/coq.8.5.1/) ) and they faced the same kind of question on distributing their big long-to-compile binary through OPAM or not. (And for cultural reasons they have stayed a bit closer to the OCaml upstream so they might have a more advanced discussion on this.)

I'm looking at the 4.03+coqide issue right now and will try to send a fix to coqdev soon.

**Comment by gasche** [comment]
I sent a PR against coq in coq/coq#228 -- I haven't been able to check yet whether this is the only build error.
