### ISSUE TITLE
opam init with rootdir

### ISSUE THREAD

**Issue by pascalito** [ocaml/opam-repository#746]
I ran:

> sudo opam init --root=/usr/local/opam

I move the opam config in the site-wide /etc/bash.bashrc config file.
I ran a new terminal.

> echo $OPAMROOT
> -> /usr/local/opam

But:

> sudo opam install ocp-build
> -> tells me that opam is not initialized
> -> Please run 'opam init' first to initialize the state of OPAM.

Is it an issue?

**Comment by RandomDSdevel** [comment]
Just wanted to let you guys know that that [link](https://github.com/OCamlPro/opam/issues/398) to OPAM Issue #389 is broken because OCamlPro seems to have disabled GitHub issues for its fork of the OCaml repository.  It should be replaced with a [link](https://github.com/ocaml/opam/issues/398) to the main OCaml repository's Issue #389.

**Comment by amirmc** [comment]
I just edited the comment to include the new link. Thanks.

**Comment by RandomDSdevel** [comment]
@amirmc:  You're welcome!
