### ISSUE TITLE
2.0 : circular dependencies for ber switches

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#7543]
```
% opam sw create --no-sw modular-implicits ocaml-variants.4.02.1+modular-implicits-ber 
[ERROR] Could not resolve set of base packages:
        The actions to process have cyclic dependencies:
          - ∗  ocaml-variants.4.02.1+modular-implicits-ber -> ∗
        ocaml.4.02.1 -> ∗  base-metaocaml-ocamlfind.base ->
        ∗  ocaml-variants.4.02.1+modular-implicits-ber


Switch initialisation failed, clean up ? ('n' will leave the switch partially
installed) [Y/n] y
```

Basically, `base-metaocaml-ocamlfind` needs `ocaml` which needs `ocaml-variants` and then full circle. I guess something went wrong while rewriting the repository.

@yallop This scheme is a bit contrived. Why not provide an alternative ocamlfind version ? 

cc @AltGr

**Comment by yallop** [comment]
> Why not provide an alternative ocamlfind version ? 

I'm open to suggestions.  But I'd rather not maintain a parallel stream of `ocamlfind` releases.  The current scheme has the advantage that it automatically works with each new `ocamlfind` release, since it just installs new toolchain config, not new software.

**Comment by Drup** [comment]
@yallop Oh, I see. it's just a config file, not a complete ocamlfind. Then it's the dependency towards `ocaml` which is wrong.

Alternatively, you could just remove the need for `metaocamlc`.

**Comment by AltGr** [comment]
Ah, the conversion from 1.2 to 2.0 assumes dependencies to ocaml, which is probably the issue here ?
There is actually an hardcoded list [here](https://github.com/ocaml/opam/blob/311c526a1d6565ee130493484889d6eb3886de1c/src/tools/opam_format_upgrade.ml#L122-L127) that is used for conversion (I first started with gathering all deps of all compilers for that purpose, but that ended up including stuff like lwt...)

Related: a feature proposal to have stuff coming with the compiler install, but that doesn't have to be a dependency of the compiler -- see https://github.com/ocaml/opam/issues/2649

**Comment by AltGr** [comment]
This was not-really-fixed by adding `base-metaocaml-ocamlfind` to the hardcoded set of packages long ago, but https://github.com/ocaml/opam/pull/3054 now provides a real fix :)
