### ISSUE TITLE
git 1.10.0 fails to install with ocpib-endian 0.3

### ISSUE THREAD

**Issue by talex5** [ocaml/opam-repository#8689]
Not sure why opam picked such an old version of ocplib-endian, but:
```
# File "src/git_misc.ml", line 49, characters 35-45:
# Error: This expression has type bytes but an expression was expected of type
#          string
```

**Comment by dbuenzli** [comment]
`git` has no direct dependency on `ocplib-endian` so either:

1. `git` is missing a direct dependency on `ocplib-endian` and in this case ping @samoht who is the maintainer of this package.
2. The package gets pulled-in because of `cstruct` and a constraint is missing on `ocplib-endian` there and ping @avsm who is the maintainer of this package.

**Comment by samoht** [comment]
Line 49 is:

```
  EndianString.BigEndian.set_int32 str_buffer 0 i;
```

so yes, ocaml-git is missing a dependency to `ocplib-endian`. I'll fix that.
