### ISSUE TITLE
there are lots of < 4.03 bounds blocking using ocaml 4.04.* with coq

### ISSUE THREAD

**Issue by cartazio** [ocaml/opam-repository#9840]
```
15:22:18 ~/l/m/mathcomp $ opam install camlp5
[ERROR] camlp5 is not available because your system doesn't comply with ocaml-version >= "1.07" & ocaml-version <= "4.03.0".
15:23:30 ~/l/m/mathcomp $ ocaml --version
The OCaml toplevel, version 4.04.2
```
is but one of them.

is there any way to fix that locally (like ignore bounds flags?)

**Comment by dbuenzli** [comment]
Could you please make an `opam update` to see if the problem persists and report the output of `opam config report`. I suspect you are using the broken internal constraint solver, if you do please install an external solver otherwise you will constantly run into problems.

The latest version of `camlp5` [does](https://github.com/ocaml/opam-repository/blob/master/packages/camlp5/camlp5.7.01/opam#L10) support 4.04.* and I just installed coq without problem in a 4.04.2 switch.

**Comment by cartazio** [comment]
thanks that seems to solve it

i guess the 'name.version' notation opam uses also confused me
